# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test Staging"
  lane :test_staging do
    scan(
      project: "PokemonCards.xcodeproj",
      devices: ["iPhone 13"],
      scheme: "Staging"
    )
  end

  desc "Test Production" 
  lane :test_production do
    scan(
      project: "PokemonCards.xcodeproj",
      devices: ["iPhone 13"],
      scheme: "Production",
      output_directory: "test-output",
      include_simulator_logs: true
    )
  end
end
